services:
  finsights:
    build: .
    image: finsights
    container_name: finsights
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
